[build]
  publish = "static"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.11"  # Cambiado de 3.9 a 3.11

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/chipi_api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
